import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer, request as httpRequest } from 'node:http';
import { AuthenticationError, AuthorizationError } from '../src/security/accessControl.js';
import { createEvidenceAssuranceExportApprovalHandler } from '../src/evidence/evidenceAssuranceExportApprovalHandler.js';

async function listen(handler){const server=createServer((req,res)=>handler.handle(req,res));await new Promise((resolve)=>server.listen(0,'127.0.0.1',resolve));return{server,port:server.address().port};}
function close(server){return new Promise((resolve,reject)=>{server.closeAllConnections?.();server.close((error)=>error?reject(error):resolve());});}
function call(port,method,path,body,headers={}){return new Promise((resolve,reject)=>{const bytes=body===null?null:Buffer.from(JSON.stringify(body));const req=httpRequest({host:'127.0.0.1',port,method,path,headers:{connection:'close',...(bytes?{'content-type':'application/json','content-length':bytes.length}:{}),...headers}},(res)=>{const chunks=[];res.on('data',(chunk)=>chunks.push(chunk));res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(Buffer.concat(chunks).toString('utf8'))}));});req.on('error',reject);req.end(bytes);});}
function fixture(){const registry={requestAssuranceExport(_t,evidenceId,input,context){return{duplicate:false,request:{requestId:`AER-${'1'.repeat(32)}`,evidenceId,requestedBy:context.actor,state:'pending',...input}};},approveAssuranceExport(_t,requestId,context){return{requestId,state:'approved',approvals:[{actor:context.actor}]};},rejectAssuranceExport(){},cancelAssuranceExport(){},assuranceExportApproval(){},assuranceExportApprovals(){return[];},assuranceExportApprovalStatus(){return{status:'ready'};},createAssuranceBundle(){return{approval:{state:'consumed'},result:{bundle:{bundleId:`ASB-${'2'.repeat(32)}`}}};}};const gateway={mode:'api-key',async authenticate(req){const key=req.headers['x-api-key'];if(!key)throw new AuthenticationError();if(key==='manager')return{subject:'manager.one',tenantId:'tenant-a',keyId:'m',permissions:['evidence:export']};return{subject:'admin.one',tenantId:'tenant-a',keyId:'a',permissions:['privileged:approve','governance:read','evidence:export']};},authorise(principal,permission){const mapped=permission==='evidence:export-request'||permission==='evidence:export-materialize'?'evidence:export':permission==='evidence:export-approve'?'privileged:approve':permission;if(!principal.permissions.includes(mapped))throw new AuthorizationError();}};return createEvidenceAssuranceExportApprovalHandler({registry,authenticationGateway:gateway});}

test('manager requests and compliance administrator approves a disclosure',async(t)=>{const{server,port}=await listen(fixture());t.after(()=>close(server));const evidenceId=`EVD-${'3'.repeat(32)}`;const requested=await call(port,'POST',`/api/workforce-audit/evidence/${evidenceId}/assurance-export-requests`,{version:1,recipientId:'auditor',purpose:'Independent external assurance examination',confirmation:`REQUEST EXPORT ${evidenceId} V1 TO auditor`},{'x-api-key':'manager'});assert.equal(requested.status,202);const id=requested.body.data.request.requestId;const approved=await call(port,'POST',`/api/workforce-audit/assurance-export-requests/${id}/approve`,{}, {'x-api-key':'admin'});assert.equal(approved.status,200);assert.equal(approved.body.data.state,'approved');});

test('manager cannot use compliance approval route',async(t)=>{const{server,port}=await listen(fixture());t.after(()=>close(server));const id=`AER-${'4'.repeat(32)}`;const response=await call(port,'POST',`/api/workforce-audit/assurance-export-requests/${id}/approve`,{}, {'x-api-key':'manager'});assert.equal(response.status,403);});

test('approved request materialisation accepts only approval ID and exact confirmation',async(t)=>{const{server,port}=await listen(fixture());t.after(()=>close(server));const evidenceId=`EVD-${'5'.repeat(32)}`;const id=`AER-${'6'.repeat(32)}`;const response=await call(port,'POST',`/api/workforce-audit/evidence/${evidenceId}/assurance-bundles`,{approvalRequestId:id,confirmation:`MATERIALIZE EXPORT ${id}`},{'x-api-key':'manager'});assert.equal(response.status,200);assert.equal(response.body.data.approval.state,'consumed');});
